name: pathfinder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13 
  - numpy
  - numba
  - pyyaml
  - tqdm
  - xarray
  - netcdf4
  - pandas
  - geopandas
  - scipy
  - scikit-image
  - cartopy
  - pyproj
  - utm
  - basemap
  - shapely
  - owslib
  - matplotlib
  - seaborn
  - cmcrameri
  - cmasher
  - cmocean
  - ipykernel
  - pyqt
  - pip
  - pip:
      - pyrpca   # comes from PyPI, not conda